overwrite: true
schema: https://docs.github.com/public/schema.docs.graphql
documents: src/gql/**
generates:
  src/gql/sdk/sdk.generated.ts:
    plugins:
      - typescript
      - typescript-operations
      - typescript-graphql-request
    config:
      gqlImport: graphql-request#gql
      enumsAsTypes: true
