name: CI

on:
  push:
    branches:
      - main
      - renovate/*
  pull_request:
    branches:
      - main
  workflow_call:
    inputs:
      version:
        description: The npm version
        default: ""
        required: false
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npx nx run-many --target lint

      - name: Run Prettier
        run: npx prettier --check .

      - name: Run CSpell
        run: npx cspell "**/*.*"

  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npx nx run-many --target build

      - name: Set Version
        if: inputs.version != ''
        run: npx nx run-many --target version --args="--version=${{ inputs.version }}"

      - name: Upload Builds
        uses: actions/upload-artifact@v5
        with:
          name: Build
          path: dist

  test:
    name: Test

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Test
        run: npx nx run-many --target test -- --ci --coverage

      - name: Codecov
        uses: codecov/codecov-action@v5.5.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: coverage

  e2e:
    strategy:
      fail-fast: true
      max-parallel: 3
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        node:
          - 18
          - 20
          - 21

    name: E2E Test (Node ${{ matrix.node }} on ${{ matrix.os }})

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run E2E Tests
        run: npx nx run-many --target e2e -- --ci
        env:
          E2E_GITHUB_USERNAME: ${{ secrets.E2E_GITHUB_USERNAME }}
          E2E_GITHUB_PAT: ${{ secrets.E2E_GITHUB_PAT }}
          E2E_GITLAB_USERNAME: ${{ secrets.E2E_GITLAB_USERNAME }}
          E2E_GITLAB_PAT: ${{ secrets.E2E_GITLAB_PAT }}
